### ISSUE TITLE
Tracking Issue: Things to address in 1.1.4

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#1035]
Below is a list of potential things to address in 1.1.4 and near-future updates closely following it.

## Things to address, in order of priority

Will help fix actions / compilation seemingly failing (while still producing an output jar) on 1.17+ (we still need https://github.com/IrisShaders/Iris/issues/1081 addressed though):

- [x] https://github.com/IrisShaders/Iris/issues/1017

Fix cameraPosition / previousCameraPosition not being shifted into a reasonable range:

- [x] https://github.com/IrisShaders/Iris/issues/334
- [x] https://github.com/IrisShaders/Iris/issues/423

Colored shadows are incorrectly rendered with blending enabled:

- [x] https://github.com/IrisShaders/Iris/issues/483
- [x] https://github.com/IrisShaders/Iris/issues/987

Fix underwater reflections / vertex normals:

- [x] https://github.com/IrisShaders/Iris/issues/500
- [x] https://github.com/IrisShaders/Iris/issues/542
- [x] https://github.com/IrisShaders/Iris/issues/625
- [x] https://github.com/IrisShaders/Iris/issues/961

Fix Iris not falling back to vanilla shader programs if the shader pack doesn't override all programs:

- [x] https://github.com/IrisShaders/Iris/issues/736
- [x] https://github.com/IrisShaders/Iris/issues/867
- [x] https://github.com/IrisShaders/Iris/issues/929
- [x] https://github.com/IrisShaders/Iris/issues/954
- [x] https://github.com/IrisShaders/Iris/issues/1097
- [x] Remember that the blend mode override should be OFF for the fallback shadow programs.

Don't assume that the pipeline is always initialized when rendering:

- [x] https://github.com/IrisShaders/Iris/issues/492
- [x] https://github.com/IrisShaders/Iris/issues/491

Make alpha test overrides work fully on 1.16 (similar to how blend mode overrides are implemented):

- [x] https://github.com/IrisShaders/Iris/issues/219

Misc shaders.properties things:

- [x] https://github.com/IrisShaders/Iris/issues/129
- [x] https://github.com/IrisShaders/Iris/issues/343
- [x] https://github.com/IrisShaders/Iris/issues/1031

Miscellaneous bug fixes:

- [x] https://github.com/IrisShaders/Iris/issues/1032

Internal refactors:

- [x] https://github.com/IrisShaders/Iris/pull/992
- [x] https://github.com/IrisShaders/Iris/pull/925
- [x] https://github.com/IrisShaders/Iris/pull/917

**Comment by IMS212** [comment]
Geometry shader support will likely need to be pushed back as there’s some really weird behavior regarding adding it into the vanilla shader.
