### ISSUE TITLE
Tracking issue for sodium compatibility

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#44]
Known issues:

* [x] Can't reload terrain / water shaders (it says successful, but the terrain shaders in use aren't changed)
* [x] Fog culling should be disabled for now because many shaders don't use fog, or use custom behavior
* [x] Translucent blocks render incorrectly (all bunched up) with AMD on Windows with some shader packs
     * This appears to be an issue with the Sildur's gbuffers_water in particular - if you delete gbuffers_water the water no longer gets bunched up but obviously it looks wrong in different ways because it's the wrong program
* [ ] `ftransform()` is not properly replaced

**Comment by coderbot16** [comment]
As it turns out, the water flickering occurs on plain Iris too: https://github.com/IrisShaders/Iris/issues/49. I'm removing it from here.

**Comment by coderbot16** [comment]
* [ ] The fabulous graphics option is still available in the Sodium video settings menu, even though Iris reverts it to Fancy once you hit Apply.

**Comment by coderbot16** [comment]
Closing this in favor of #158 since all but one of the issues listed here is resolved.
